version: "3.7"

services:
  db:
    image: postgres
    network_mode: bridge
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=testdb
    ports:
      - 5433:5432
    restart: always